language: ruby
rvm:
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- ree
- jruby-19mode
- jruby-18mode
- rbx-18mode
- rbx-19mode
matrix:
allow_failures:
- rvm: rbx-18mode
- rvm: rbx-19mode
- rvm: jruby-19mode
- rvm: jruby-18mode

# uncomment this line if your project needs to run something other than `rake`:
# # script: bundle exec rspec spec
